SELECT DISTINCT EMPLOYEES.eid 
  FROM FLIGHTS,AIRCRAFTS,SCHEDULE,CERTIFIED,EMPLOYEES
  WHERE FLIGHTS.flno = SCHEDULE.flno,AIRCRAFTS.aid = SCHEDULE.aid,SCHEDULE.aid = CERTIFIED.aid,EMPLOYEES.eid = CERTIFIED.eid
