SELECT DISTINCT EMPLOYEES.eid 
  FROM FLIGHTS,AIRCRAFTS,SCHEDULE,CERTIFIED,EMPLOYEES
  WHERE FLIGHTS.flno = SCHEDULE.flno 
    AND SCHEDULE.aid = AIRCRAFTS.aid 
    AND SCHEDULE.aid = CERTIFIED.aid
    AND EMPLOYEES.eid = CERTIFIED.eid
