
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Mar 19 17:00:58 SGT 2021
//----------------------------------------------------

package qp.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ORDERBY = 18;
  public static final int WHERE = 16;
  public static final int FROM = 15;
  public static final int GROUPBY = 17;
  public static final int RIGHTBRACKET = 5;
  public static final int DESC = 28;
  public static final int SELECT = 14;
  public static final int EQUAL = 12;
  public static final int NOTEQUAL = 13;
  public static final int SUM = 24;
  public static final int ALL = 21;
  public static final int LTOE = 10;
  public static final int STAR = 7;
  public static final int ID = 2;
  public static final int GTOE = 11;
  public static final int COMMA = 3;
  public static final int INTERSECT = 20;
  public static final int LESSTHAN = 8;
  public static final int EOF = 0;
  public static final int STRINGLIT = 29;
  public static final int DISTINCT = 27;
  public static final int UNION = 19;
  public static final int LEFTBRACKET = 4;
  public static final int AVG = 26;
  public static final int error = 1;
  public static final int DOT = 6;
  public static final int MIN = 23;
  public static final int MAX = 22;
  public static final int COUNT = 25;
  public static final int GREATERTHAN = 9;
}

